### PR TITLE
Make django-honeypot compatible with django 2.2 by porting HoneypotMiddleware to newstyle middleware

### PR DESCRIPTION
**Pull request by Psycojoker**
Hello,

Everything should be in the title. I can also try to do the modification to prepare a new release if you want :)

Reference documentation in case of https://docs.djangoproject.com/en/2.2/topics/http/middleware/

Thanks for this project!

### CODE REVIEW

**Comment by jamesturk** [comment]
thanks for this!  I wonder if you'd have a chance to look at the failing tests, I'll try to soon as well if not :)

**Comment by Psycojoker** [comment]
Oh, totally missed the tests, sorry :sweat_smile: 

That should be good now :) (at least tox is happy on my computer)

**Comment by Psycojoker** [comment]
And now really good >.>

**Comment by aleray** [comment]
Hi, would it be possible to merge @Psycojoker branch and make a release? Would be very helpful. Thanks

**Comment by jamesturk** [comment]
merged, thanks for the ping.  I'll work on a release this afternoon or tomorrow

**Comment by aleray** [comment]
@jamesturk @Psycojoker thanks a lot!

**Pull request merged**
